<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-8J9VN6K" failures="2" tests="7" name="Test" time="63.802" errors="0" timestamp="2024-09-14T18:12:26 IST">
  <testcase classname="testCases.TC002_LoginTest" name="verify_login" time="2.805"/>
  <testcase classname="testCases.TC001_AccountRegistrationTest" name="verify_account_registration" time="2.009">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC001_AccountRegistrationTest.verify_account_registration(TC001_AccountRegistrationTest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verify_account_registration -->
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="2.707"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="11.46"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="3.144">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC003_LoginDDT.verify_loginDDT(TC003_LoginDDT.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="13.011"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="2.279"/>
</testsuite> <!-- Test -->
